# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG
logging.level.nz.net.ultraq.thymeleaf=DEBUG



# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/plantcare
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


server.port=8080

app.simulation.enabled=true
app.simulation.interval-seconds=30